# Generated by Django 4.1.4 on 2023-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=200, verbose_name="이름"),
        ),
    ]
