# Generated by Django 4.1.4 on 2023-01-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="count",
            field=models.IntegerField(default=0, verbose_name="갯수"),
        ),
    ]
