# Generated by Django 4.1.4 on 2023-01-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_item_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="alcohol",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
