# Generated by Django 4.1.4 on 2023-01-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_item_alcohol"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="shop",),
        migrations.AddField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=1, verbose_name="작성날짜"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="title",
            field=models.CharField(default=1, max_length=200, verbose_name="제목"),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Order",),
        migrations.DeleteModel(name="Shop",),
    ]
