# Generated by Django 4.1.4 on 2023-01-13 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0006_remove_item_shop_item_created_at_item_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="alcohol",),
        migrations.RemoveField(model_name="item", name="name",),
        migrations.AddField(
            model_name="item",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="content",
            field=models.TextField(default=1, verbose_name="내용"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정날짜"),
        ),
        migrations.AlterField(
            model_name="item",
            name="count",
            field=models.IntegerField(default=0, verbose_name="개수"),
        ),
    ]
