# Generated by Django 4.1.4 on 2023-01-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="image", new_name="product_image",
        ),
    ]
