# Generated by Django 4.1.4 on 2023-01-13 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="Answer", new_name="answer",
        ),
    ]
