# Generated by Django 4.1.4 on 2023-01-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_answer_voter_question_voter"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="view_cnt",
            field=models.BigIntegerField(default=0),
        ),
    ]
