# Generated by Django 4.1.4 on 2023-01-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_question_view_cnt"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=30)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.question"
                    ),
                ),
            ],
        ),
    ]
