# Generated by Django 4.1.4 on 2022-12-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0004_fruit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=100, verbose_name="질문")),
                ("pub_date", models.DateTimeField(verbose_name="작성날짜")),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                (
                    "votes",
                    models.ImageField(default=0, upload_to="", verbose_name="투표"),
                ),
                (
                    "question_text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam.question",
                        verbose_name="연결된 질문",
                    ),
                ),
            ],
        ),
    ]
