# Generated by Django 4.1.4 on 2022-12-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("imae", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
