# Generated by Django 4.1.4 on 2022-12-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="photo", old_name="imae", new_name="image",),
    ]
